# Generated by Django 3.1.3 on 2020-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpa_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
