# Generated by Django 3.1.3 on 2020-11-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpa_tool', '0002_auto_20201125_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
    ]
